2020-10-30 20:19:23,796 ERROR: Exception on /user/albert [GET] [in d:\program files\python35\webmssql\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "d:\program files\python35\webmssql\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\program files\python35\webmssql\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\program files\python35\webmssql\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\program files\python35\webmssql\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "d:\program files\python35\webmssql\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\program files\python35\webmssql\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\program files\python35\webmssql\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\Program Files\Python35\webmssql\app\routes.py", line 70, in user
    return render_template('user.html', user=user, posts=posts)
  File "d:\program files\python35\webmssql\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "d:\program files\python35\webmssql\venv\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "d:\program files\python35\webmssql\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "d:\program files\python35\webmssql\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "d:\program files\python35\webmssql\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\Program Files\Python35\webmssql\app\templates\user.html", line 3, in top-level template code
    {% extends "base.html" %}
  File "D:\Program Files\Python35\webmssql\app\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "D:\Program Files\Python35\webmssql\app\templates\user.html", line 15, in block "content"
    <p><a href="{{ url_for('edit_profile') }}">Edit your profile</a></p>
  File "d:\program files\python35\webmssql\venv\lib\site-packages\flask\helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\program files\python35\webmssql\venv\lib\site-packages\flask\app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\program files\python35\webmssql\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "d:\program files\python35\webmssql\venv\lib\site-packages\flask\helpers.py", line 323, in url_for
    force_external=external)
  File "d:\program files\python35\webmssql\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'edit_profile'. Did you mean 'user' instead?
2020-10-30 20:19:48,374 ERROR: Exception on /user/albert [GET] [in d:\program files\python35\webmssql\venv\lib\site-packages\flask\app.py:1560]
Traceback (most recent call last):
  File "d:\program files\python35\webmssql\venv\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\program files\python35\webmssql\venv\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\program files\python35\webmssql\venv\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\program files\python35\webmssql\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "d:\program files\python35\webmssql\venv\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\program files\python35\webmssql\venv\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "d:\program files\python35\webmssql\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\Program Files\Python35\webmssql\app\routes.py", line 70, in user
    return render_template('user.html', user=user, posts=posts)
  File "d:\program files\python35\webmssql\venv\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "d:\program files\python35\webmssql\venv\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "d:\program files\python35\webmssql\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "d:\program files\python35\webmssql\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "d:\program files\python35\webmssql\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\Program Files\Python35\webmssql\app\templates\user.html", line 3, in top-level template code
    {% extends "base.html" %}
  File "D:\Program Files\Python35\webmssql\app\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "D:\Program Files\Python35\webmssql\app\templates\user.html", line 15, in block "content"
    <p><a href="{{ url_for('edit_profile') }}">Edit your profile</a></p>
  File "d:\program files\python35\webmssql\venv\lib\site-packages\flask\helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\program files\python35\webmssql\venv\lib\site-packages\flask\app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\program files\python35\webmssql\venv\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "d:\program files\python35\webmssql\venv\lib\site-packages\flask\helpers.py", line 323, in url_for
    force_external=external)
  File "d:\program files\python35\webmssql\venv\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'edit_profile'. Did you mean 'user' instead?
